#!/bin/bash

# source function library
. ${0%/*}/wsl-functions

case "$1" in
  -h|--help|help)
    $WSCOLORERR
    echo -e "\n`basename $0` - Utility to create and edit ${MYCONFIG} file\n"
    $WSCOLORNORM
    exit 1
    ;;
esac

vi ~/${MYCONFIG}

