#!/bin/bash
# ###########################################################################
# Copyright (c) 2011, Dell Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of Dell Inc. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL DELL INC. BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# ###########################################################################
# Authors: Chris A. Poblete
# Version: 1.0.0
# ###########################################################################

MYNAME=`basename $0`
MYPATH=${0%/*}
KEEPHISTORY=0

# source function library
. ${0%/*}/wsl-functions

usage() {
  fUsageheader
  cat <<EOF
USAGE: $MYNAME CREDFILENAME [ USERNAME [PASSWORD] | -d ]

This tool encrypts the user name and password into a credential file. The file
may only be used or decrypted on the same system it was created. 

${CommonUsage1}
EOF
  $WSCOLORNORM
  exit 1
}

[ $# -lt 1 ] && usage
[ "$1" = "-h" -o "$1" = "-help" -o "$1" = "help" ] && usage
credfile="$1"
WSUSER="$2"
WSPASS="$3"

fCheckReqsOrUsage gpg

echo "${WSUSER}" | grep "^-d" >/dev/null 2>&1
if [ $? -eq 0 ]; then
  fGetCredFileContents "${credfile}"
  echo "${CREDPAIR}"
else
  echo >${credfile}
  [ -z "${WSUSER}" ] && fPromptUser 0 WSUSER "User name"
  [ -z "${WSPASS}" ] && fPromptUser 0 WSPASS "User password"
  fCreateCredFile ${credfile}
fi

exit 0

# ###########################################################################
# End of Code
# ###########################################################################
