#!/bin/bash
# ###########################################################################
# Copyright (c) 2011, Dell Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of Dell Inc. nor the names of its contributors
#      may be used to endorse or promote products derived from this software
#      without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL DELL INC. BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
# ###########################################################################
# Authors: Chris A. Poblete
# Version: 1.0.0
# ###########################################################################

MYNAME=`basename $0`

# source function library
. ${0%/*}/wsl-functions

usage() {
  fUsageheader
  cat <<EOF
USAGE: $MYNAME CLASS SELECTOR1=VALUE1 [SELECTOR2=VALUE2 ...]

Sends SOAP message with WS-MAN GET command. 
Enclose the value in double quotes when the value contains space.

${CommonUsage1}
EOF
  $WSCOLORNORM
  exit 1
}

fCheckReqsOrUsage

[ $# -lt 1 ] && usage
while [ ! -z "$1" ]; do
  case "$1" in
    -h|-help|help ) usage
      ;;
    * ) echo "$1" | grep '=' >/dev/null 2>&1
      if [ $? -ne 0 ]; then
        [ -z "${CLASS}" ] && export CLASS="$1" && shift && continue
      else
        Name=$(echo $1 | cut -d '=' -f1 )
        Value=$(echo $1 | cut -d '=' -f2- )
        INSTANCESELECTOR="${INSTANCESELECTOR}<wsman:Selector Name=\"${Name}\">${Value}</wsman:Selector>"
        CheckRsp=${Name}
      fi
      ;;
  esac
  shift
done

# initializations
fGetTarget
fSetWGET
fNormalizeClass

doget() {
  fGetUUID
  fReqRspNext
cat <<EOF >${REQUESTFILE}
${WSENVELOPEHEADER}
  <s:Header>
    <wsa:Action s:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/09/transfer/Get</wsa:Action>
    ${WSCOMMONHEADER}
    <wsman:ResourceURI s:mustUnderstand="true">${CLASS}</wsman:ResourceURI>
    <wsa:MessageID s:mustUnderstand="true">${UUID}</wsa:MessageID>
    <wsa:ReplyTo>
      <wsa:Address>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:Address>
    </wsa:ReplyTo>
    <wsman:SelectorSet>
      ${INSTANCESELECTOR}
    </wsman:SelectorSet>
  </s:Header>
  <s:Body/>
</s:Envelope>
EOF
  fNormalizeXML ${REQUESTFILE}
  fDumpRequestFile
  fSendRequest
  
  grep ":${CheckRsp}\>" ${RESPONSEFILE} 2>&1 >/dev/null
  export STAT=$?
}

[ ${OUTLEVEL} -ge 3 ] && echo "NOTE: Get operation may take time to reply."
doget
fNormalizeXML ${RESPONSEFILE}

fDisplayResponse ${RESPONSEFILE}

/bin/cp ${RESPONSEFILE} ${RETURNFILE}
[ ${OUTLEVEL} -ge 3 ] && echo "Output is saved to ${RETURNFILE}"
exit ${STAT}

# ###########################################################################
# End of Code
# ###########################################################################
